### PR TITLE
Add integration for reading cached .sha256 file

### PR DESCRIPTION
**Pull request by sansmoraxz**
Some download tools already create .sha256 checksums such as https://github.com/pythongosssss/ComfyUI-Custom-Scripts

This modification will use that computed has rather than recalculating it separately.

### CODE REVIEW

**Comment by Kinglord** [comment]
This looks good, but when they worked, I think I remember custom scripts would pull in and built some kind of data file as well? I already support 3 different kinds now in order to totally avoid calls, if you could share the data format for this I can support it so I don't even need the hash for a lookup 😄 I tried to do this myself but the script in custom scripts to get civit info don't seem to work anymore.

**Comment by sansmoraxz** [comment]
It's the same as what you implemented, just dump a plain text of the calculated hash. If you want you can incorporate it into your functionality so that rebuilding cache is faster. Only time I have seen the lookups not working properly is when those are from archived files such as `zip`.

Was thinking of building a model manager of my own as [ComfyUI-Model-Manager](https://github.com/hayden-fr/ComfyUI-Model-Manager) wasn't cutting it for my usecase. It has a downloader which simplifies remotely managing models across various disks. But searching for loras or looking up what it does is a bit more hectic in it.

Some sort of pagination / virtual table may be required for large number of loras, but I am not sure how to pull it off without incorporating a heavy ui framework.

**Comment by Kinglord** [comment]
Right, I was just wondering if you had an example file from when it was working you could share since I can't generate one anymore. 😁

I messed with Model Manager as well before building this, I just wanted something fast without extra fluff. I use a downloader on one of my other sidebars but I don't do anything fancy because I'm just dealing with LECOs there that are generally tiny. It's a me think but I also hate things that clutter up my model files with other associated files (the main reason I didn't use the custom scripts stuff back when it did work). My sidebar works well with large datasets (I have over 9, been testing with people that have 10 or even 20k+) without sorting but I need to re-address how I handle such large collections with sorting enabled. You can have the python do a lot of the data work for you so it's not swamping your FE.

Anyway, happy to chat more if you want to DM me or whatever, I'll probably close this out once I merge this in. 😉

**Comment by sansmoraxz** [comment]
You know what I think that was some other tool that was probably generating the hashes. Restesting with [pythongosssss/ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) looks like the file format is with no ext+.sha256.

You may be onto something with different tools polluting models folder.

**Comment by sansmoraxz** [comment]
How my lora folder is currently:-
image

And sample file
[1dkXLP.safetensors.sha256](https://github.com/user-attachments/files/17534541/1dkXLP.safetensors.sha256.txt)

~Added .txt as github doest directly allow the original extension~

**Comment by Kinglord** [comment]
Thanks for that file, what does the corresponding txt file have in it if I might ask? I added a lot of data formats in my last release, so if I can understand what you have setup I can probably squeeze it into my next update.

**Comment by Kinglord** [comment]
I went ahead and implemented a slightly different version of this which should pick up these local hash files, I found some old stuff I had and the txt files were mostly notes and not useful metadata. I'd like to extend this later to do a proper metadata hash and pull information out of the model files for things like custom loras, etc. But not today 😁

**Pull request closed without merging**
